export const data = [
    {
        asset: 'HYPE',
        price: '$23.15',
        tvl: '$1,031,020,486.33',
        apy: '2.31%',
        commission: '2%',
        product: 'Proof-of-Stake',
        ecosystem: 'Hyperliquid',
    },
    {
        asset: 'TRX',
        price: '$0.26',
        tvl: '$231,341,492.66',
        apy: '4.65%',
        commission: '5%',
        product: 'Proof-of-Stake',
        ecosystem: 'Tron',
    },
    {
        asset: 'SOL',
        price: '$1,800.00',
        tvl: '$1,200,000,000.00',
        apy: '3.50%',
        commission: '10%',
        product: 'Proof-of-Stake',
        ecosystem: 'Ethereum',
    },
    {
        asset: 'ATOM',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
     {
        asset: 'TIA',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'ROM',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'APT',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'DYDX',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'STRK',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'NEAR',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'BAND',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },

];  