export const data = [
    {
        asset: 'RON',
        id: 'ronin',
        price: '$',
        apy: '12.56%',
        commission: '10%',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/Logo_Ronin.png',
        logo: '/logos/Logo_Ronin.png',
        stakingLink: 'https://app.roninchain.com/staking',
    },
    {
        asset: 'NEAR',
        id: 'near',
        price: '$',
        apy: '9.74%',
        commission: '7%',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/near.png',
        logo: '/logos/near.png',
        stakingLink: 'https://app.mynearwallet.com/staking/', 
    },
    {
        asset: 'RIO',
        id: 'realio-network',
        price: '-',
        apy: '-',
        commission: '-',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/rio_icon.png',
        logo: '/logos/rio_icon.png',
        stakingLink: 'https://app.realio.network/staking', 
    },
    {
        asset: 'BEAMX',
        id: 'beam-2',
        price: '-',
        apy: '-',
        commission: '-',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/beam.jpg',
        logo: '/logos/beam.jpg',
        stakingLink: 'https://swap.onbeam.com/#/swap', 
    },
    {
        asset: 'XAI',
        id: 'xai',
        price: '-',
        apy: '-',
        commission: '-',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/xai.jpg',
        logo: '/logos/xai.jpg',
        stakingLink: 'https://app.xai.games/', 
    },
    {
        asset: 'CARV',
        id: 'carv',
        price: '-',
        apy: '-',
        commission: '-',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/Logo_Carv.png',
        logo: '/logos/Logo_Carv.png',
        stakingLink: 'https://explorer.carv.io/verifiers',
    },
    {
        asset: 'SOPH',
        id: 'sophon',
        price: '-',
        apy: '-',
        commission: '-',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/sophon.jpg',
        logo: '/logos/sophon.jpg',
        stakingLink: 'https://sophon.network/stake', // Add staking link here
    },
    {
        asset: 'HYC',
        id: 'hychain',
        price: '-',
        apy: '-',
        commission: '-',
        product: 'Proof-of-Stake',
        ecosystem: '/logos/hychain.jpg',
        logo: '/logos/hychain.jpg',
        stakingLink: 'https://explorer.hychain.com/',
    },
];