export const data = [
    {
        asset: 'HYPE',
        id: 'hyperliquid',
        price: '$23.15',
        tvl: '$1,031,020,486.33',
        apy: '2.31%',
        commission: '2%',
        product: 'Proof-of-Stake',
        ecosystem: 'Hyperliquid',
    },
    {
        asset: 'TRX',
        id: 'tron',
        price: '$0.26',
        tvl: '$231,341,492.66',
        apy: '4.65%',
        commission: '5%',
        product: 'Proof-of-Stake',
        ecosystem: 'Tron',
    },
    {
        asset: 'SOL',
        id: 'solana',
        price: '$1,800.00',
        tvl: '$1,200,000,000.00',
        apy: '3.50%',
        commission: '10%',
        product: 'Proof-of-Stake',
        ecosystem: 'Ethereum',
    },
    {
        asset: 'ATOM',
        id: 'cosmos',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
     {
        asset: 'TIA',
        id: 'celestia',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'RON',
        id: 'ronin',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'APT',
        id: 'aptos',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'DYDX',
        id: 'dydx-chain',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'STRK',
        id: 'starknet',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'NEAR',
        id: 'near',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },
    {
        asset: 'BAND',
        id: 'band-protocol',
        price: '$300.00',
        tvl: '$500,000,000.00',
        apy: '5.00%',
        commission: '8%',
        product: 'Proof-of-Stake',
        ecosystem: 'Binance Smart Chain',
    },

];  